import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import Header from "./component/layout/Header";
import Footer from "./component/layout/Footer";
import PreloaderHost from "./component/ui/PreloaderHost";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`h-full antialiased ${plusJakartaSans.variable}`}>
      <body className="min-h-full flex flex-col">
        <PreloaderHost />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
