// Auto-generated from section module styles.

export const aboutUsStyles = {
  actions: 'about-us-actions',
  cardShell: 'about-us-panel',
  content: 'about-us-content',
  description: 'about-us-description',
  eyebrow: 'about-us-eyebrow',
  heading: 'about-us-heading',
  image: 'about-us-image',
  imageCard: 'about-us-imageCard',
  imageGlow: 'about-us-imageGlow',
  layout: 'about-us-inner',
  section: 'about-us-section',
  media: 'about-us-visual',
} as const

export const coreValuesStyles = {
  copy: 'core-values-copy',
  icon: 'core-values-icon',
  iconWrap: 'core-values-iconWrap',
  section: 'core-values-section',
  valueDescription: 'core-values-valueDescription',
  valueItem: 'core-values-valueItem',
  valuesList: 'core-values-valuesList',
  valueTitle: 'core-values-valueTitle',
} as const

export const faqStyles = {
  accordion: 'faq-accordion',
  answer: 'faq-answer',
  chevron: 'faq-chevron',
  chevronOpen: 'faq-chevronOpen',
  copyBlock: 'faq-copyBlock',
  eyebrow: 'faq-eyebrow',
  heading: 'faq-heading',
  item: 'faq-item',
  itemOpen: 'faq-itemOpen',
  panel: 'faq-panel',
  question: 'faq-question',
  questionIcon: 'faq-questionIcon',
  questionWrap: 'faq-questionWrap',
  section: 'faq-section',
  shell: 'faq-shell',
  trigger: 'faq-trigger',
} as const

export const heroStyles = {
  actions: 'hero-actions',
  background: 'hero-background',
  backgroundFrame: 'hero-backgroundFrame',
  backgroundStack: 'hero-backgroundStack',
  content: 'hero-content',
  description: 'hero-description',
  heading: 'hero-heading',
  primaryButtonOverride: 'hero-primaryButtonOverride',
  secondaryButton: 'hero-secondaryButton',
  section: 'hero-section',
  shell: 'hero-shell',
} as const

export const homeContactStyles = {
  address: 'home-contact-address',
  contactCopy: 'home-contact-contactCopy',
  contactItem: 'home-contact-contactItem',
  contactLabel: 'home-contact-contactLabel',
  contactList: 'home-contact-contactList',
  contactValue: 'home-contact-contactValue',
  copy: 'home-contact-copy',
  description: 'home-contact-description',
  eyebrow: 'home-contact-eyebrow',
  formWrap: 'home-contact-formWrap',
  heading: 'home-contact-heading',
  icon: 'home-contact-icon',
  iconWrap: 'home-contact-iconWrap',
  section: 'home-contact-section',
  shell: 'home-contact-shell',
} as const

export const processStepStyles = {
  card: 'process-step-card',
  copy: 'process-step-copy',
  description: 'process-step-description',
  eyebrow: 'process-step-eyebrow',
  grid: 'process-step-grid',
  gridItem: 'process-step-gridItem',
  header: 'process-step-header',
  heading: 'process-step-heading',
  inner: 'process-step-inner',
  number: 'process-step-number',
  section: 'process-step-section',
  stepWord: 'process-step-stepWord',
  title: 'process-step-title',
} as const

export const serviceSectionStyles = {
  accordion: 'service-section-accordion',
  activeItem: 'service-section-activeItem',
  activeTrigger: 'service-section-activeTrigger',
  content: 'service-section-content',
  ctaWrap: 'service-section-ctaWrap',
  description: 'service-section-description',
  eyebrow: 'service-section-eyebrow',
  header: 'service-section-header',
  headerWrap: 'service-section-headerWrap',
  heading: 'service-section-heading',
  image: 'service-section-image',
  inactiveItem: 'service-section-inactiveItem',
  inactiveTrigger: 'service-section-inactiveTrigger',
  item: 'service-section-item',
  media: 'service-section-media',
  number: 'service-section-number',
  panel: 'service-section-panel',
  panelLineFour: 'service-section-panelLineFour',
  panelLineOne: 'service-section-panelLineOne',
  panelLineThree: 'service-section-panelLineThree',
  panelLineTwo: 'service-section-panelLineTwo',
  placeholderBackdrop: 'service-section-placeholderBackdrop',
  primaryCta: 'service-section-primaryCta',
  readMore: 'service-section-readMore',
  readMoreIcon: 'service-section-readMoreIcon',
  readMoreText: 'service-section-readMoreText',
  readMoreWrap: 'service-section-readMoreWrap',
  shell: 'service-section-shell',
  section: 'service-section-section',
  sunGlow: 'service-section-sunGlow',
  tabHint: 'service-section-tabHint',
  title: 'service-section-title',
  trigger: 'service-section-trigger',
} as const

export const teamHomeStyles = {
  accent: 'team-home-accent',
  actions: 'team-home-actions',
  card: 'team-home-card',
  cardImage: 'team-home-cardImage',
  cardMedia: 'team-home-cardMedia',
  cardMeta: 'team-home-cardMeta',
  cardName: 'team-home-cardName',
  cardOverlay: 'team-home-cardOverlay',
  cardRole: 'team-home-cardRole',
  cards: 'team-home-cards',
  copy: 'team-home-copy',
  heading: 'team-home-heading',
  headingLine: 'team-home-headingLine',
  inner: 'team-home-inner',
  section: 'team-home-section',
} as const

export const trustedPartnerStyles = {
  description: 'trusted-partner-description',
  heading: 'trusted-partner-heading',
  inner: 'trusted-partner-inner',
  panel: 'trusted-partner-panel',
  section: 'trusted-partner-section',
} as const

export const whyChooseUsStyles = {
  actions: 'why-choose-us-actions',
  badge: 'why-choose-us-badge',
  content: 'why-choose-us-content',
  controlButton: 'why-choose-us-controlButton',
  eyebrow: 'why-choose-us-eyebrow',
  featureCopy: 'why-choose-us-featureCopy',
  featureHeader: 'why-choose-us-featureHeader',
  featureIcon: 'why-choose-us-featureIcon',
  featureList: 'why-choose-us-featureList',
  featureRow: 'why-choose-us-featureRow',
  featureText: 'why-choose-us-featureText',
  featureTitle: 'why-choose-us-featureTitle',
  heading: 'why-choose-us-heading',
  image: 'why-choose-us-image',
  imageCard: 'why-choose-us-imageCard',
  imageControls: 'why-choose-us-imageControls',
  inner: 'why-choose-us-inner',
  mainGrid: 'why-choose-us-mainGrid',
  panel: 'why-choose-us-panel',
  section: 'why-choose-us-section',
  topDescription: 'why-choose-us-topDescription',
  topLeft: 'why-choose-us-topLeft',
  topRow: 'why-choose-us-topRow',
  visual: 'why-choose-us-visual',
} as const

export const whySolarStyles = {
  card: 'why-solar-card',
  cardDescription: 'why-solar-cardDescription',
  cardItem: 'why-solar-cardItem',
  cards: 'why-solar-cards',
  cardsShell: 'why-solar-cardsShell',
  cardTitle: 'why-solar-cardTitle',
  description: 'why-solar-description',
  eyebrow: 'why-solar-eyebrow',
  heading: 'why-solar-heading',
  heroCopy: 'why-solar-heroCopy',
  heroImage: 'why-solar-heroImage',
  heroShell: 'why-solar-heroShell',
  heroStage: 'why-solar-heroStage',
  highlight: 'why-solar-highlight',
  icon: 'why-solar-icon',
  iconBox: 'why-solar-iconBox',
  overlay: 'why-solar-overlay',
  section: 'why-solar-section',
  subheading: 'why-solar-subheading',
} as const


